name: Setup Branch Protection

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name (owner/repo)'
        required: true
        default: 'BETTERGOV/petition'
      branch:
        description: 'Branch to protect'
        required: true
        default: 'main'

jobs:
  setup-branch-protection:
    name: Configure Branch Protection Rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Branch Protection
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const branch = '${{ github.event.inputs.branch }}' || 'main';

            const protection = {
              required_status_checks: {
                strict: true,
                contexts: [
                  'lint-and-format',
                  'type-check', 
                  'build-check',
                  'test-e2e',
                  'security-check'
                ]
              },
              enforce_admins: true,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: false
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            };

            try {
              await github.rest.repos.updateBranchProtection({
                owner,
                repo,
                branch,
                ...protection
              });
              
              console.log(`✅ Branch protection rules applied to ${branch}`);
              console.log('Required status checks:', protection.required_status_checks.contexts);
            } catch (error) {
              console.error('❌ Failed to set up branch protection:', error.message);
              throw error;
            }

      - name: Verify Protection Rules
        run: |
          echo "Branch protection rules have been configured for the ${{ github.event.inputs.branch }} branch"
          echo "Required status checks:"
          echo "- lint-and-format"
          echo "- type-check"
          echo "- build-check" 
          echo "- test-e2e"
          echo "- security-check"
          echo ""
          echo "Additional protections:"
          echo "- Require pull request reviews"
          echo "- Dismiss stale reviews"
          echo "- Require branches to be up to date"
          echo "- Restrict force pushes"
