name: Deploy to Staging

on:
  workflow_run:
    workflows: ['Security Scan']
    types: [completed]
    branches: [develop]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    environment: staging
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      #      - name: Deploy to Cloudflare Pages (Staging)
      #        uses: cloudflare/pages-action@v1
      #        with:
      #          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      #          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      #          projectName: petition-staging
      #          directory: dist
      #          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify deployment status
        run: |
          echo "Staging deployment completed successfully"
          echo "Environment: staging"
          echo "Branch: ${{ github.ref_name }}"
